// DashboardReact/src/components/History/HistoryGraph.tsx
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  TimeScale,
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import 'chartjs-adapter-date-fns';
import type { SensorDataEx } from '../../types/sensor.types';
import './HistoryGraph.css';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  TimeScale
);

interface HistoryGraphProps {
  sensorDataEx: SensorDataEx[];
}

const HistoryGraph = ({ sensorDataEx }: HistoryGraphProps) => {
  const processData = () => {
    let maxValue = 0;
    let minValue = 100;
    const tempArray: Array<{ y: number; t: string }> = [];
    const tValveArray: Array<{ y: number; t: string }> = [];
    const tSchedArray: Array<{ y: number; t: string }> = [];
    const tCurrentArray: Array<{ y: number; t: string }> = [];
    const humidityArray: Array<{ y: number; t: string }> = [];
    const pointRadius0: number[] = [];
    const pointRadius1: number[] = [];
    const pointRadius2: number[] = [];
    const pointRadius3: number[] = [];
    const pointRadius4: number[] = [];

    for (let i = 0; i < sensorDataEx.length; i++) {
      if (i > 0) {
        const dateNewValue = new Date(sensorDataEx[i].ingestionTimestamp);
        const dateOldValue = new Date(sensorDataEx[i - 1].ingestionTimestamp);
        const diff = Math.abs(dateNewValue.getTime() - dateOldValue.getTime());
        const minutes = Math.floor(diff / 60000);

        if (minutes > 15) {
          const dateIntermediate = new Date(dateNewValue.getTime() - 10 * 60 * 1000);
          const dateIso = dateIntermediate.toISOString();

          tempArray.push({ y: sensorDataEx[i - 1].temp, t: dateIso });
          tValveArray.push({ y: sensorDataEx[i - 1].tValve, t: dateIso });
          tSchedArray.push({ y: sensorDataEx[i - 1].tScheduledTarget, t: dateIso });
          tCurrentArray.push({ y: sensorDataEx[i - 1].tCurrentTarget, t: dateIso });
          humidityArray.push({ y: sensorDataEx[i - 1].humidity, t: dateIso });

          pointRadius0.push(1);
          pointRadius1.push(1);
          pointRadius2.push(1);
          pointRadius3.push(1);
          pointRadius4.push(1);
        }
      }

      tempArray.push({ y: sensorDataEx[i].temp, t: sensorDataEx[i].ingestionTimestamp });
      tValveArray.push({ y: sensorDataEx[i].tValve, t: sensorDataEx[i].ingestionTimestamp });
      tSchedArray.push({ y: sensorDataEx[i].tScheduledTarget, t: sensorDataEx[i].ingestionTimestamp });
      tCurrentArray.push({ y: sensorDataEx[i].tCurrentTarget, t: sensorDataEx[i].ingestionTimestamp });
      humidityArray.push({ y: sensorDataEx[i].humidity, t: sensorDataEx[i].ingestionTimestamp });

      pointRadius0.push(sensorDataEx[i].setTempSended ? 4 : 1);
      pointRadius1.push(1);
      pointRadius2.push(1);
      pointRadius3.push(1);
      pointRadius4.push(1);

      // Calculate min/max
      if (maxValue < sensorDataEx[i].temp && sensorDataEx[i].temp > 0) maxValue = sensorDataEx[i].temp;
      if (maxValue < sensorDataEx[i].tValve && sensorDataEx[i].tValve > 0) maxValue = sensorDataEx[i].tValve;
      if (maxValue < sensorDataEx[i].tScheduledTarget && sensorDataEx[i].tScheduledTarget > 0)
        maxValue = sensorDataEx[i].tScheduledTarget;
      if (maxValue < sensorDataEx[i].tCurrentTarget && sensorDataEx[i].tCurrentTarget > 0)
        maxValue = sensorDataEx[i].tCurrentTarget;

      if (minValue > sensorDataEx[i].temp && sensorDataEx[i].temp > 0) minValue = sensorDataEx[i].temp;
      if (minValue > sensorDataEx[i].tValve && sensorDataEx[i].tValve > 0) minValue = sensorDataEx[i].tValve;
      if (minValue > sensorDataEx[i].tScheduledTarget && sensorDataEx[i].tScheduledTarget > 0)
        minValue = sensorDataEx[i].tScheduledTarget;
      if (minValue > sensorDataEx[i].tCurrentTarget && sensorDataEx[i].tCurrentTarget > 0)
        minValue = sensorDataEx[i].tCurrentTarget;
    }

    return {
      datasets: tempArray,
      tValveDatasets: tValveArray,
      tSchedDatasets: tSchedArray,
      tCurrentDatasets: tCurrentArray,
      humidityDatasets: humidityArray,
      pointRadius0,
      pointRadius1,
      pointRadius2,
      pointRadius3,
      pointRadius4,
      maxValue,
      minValue,
    };
  };

  const processedData = processData();

  const data = {
    datasets: [
      {
        label: 'Temp',
        data: processedData.datasets,
        backgroundColor: 'rgba(255, 61, 113, 0.3)',
        borderColor: '#ff3d71',
        tension: 0,
        fill: false,
        pointRadius: processedData.pointRadius0,
        yAxisID: 'yTemperature',
      },
      {
        label: 'T Valve',
        data: processedData.tValveDatasets,
        backgroundColor: 'rgba(51, 102, 255, 0.3)',
        borderColor: '#3366ff',
        tension: 0,
        fill: false,
        pointRadius: processedData.pointRadius1,
        hidden: true,
        yAxisID: 'yTemperature',
      },
      {
        label: 'T Scheduled',
        data: processedData.tSchedDatasets,
        backgroundColor: 'rgba(0, 214, 143, 0.3)',
        borderColor: '#00d68f',
        borderDash: [10, 5],
        tension: 0,
        fill: false,
        pointRadius: processedData.pointRadius2,
        yAxisID: 'yTemperature',
      },
      {
        label: 'T CurrentSched',
        data: processedData.tCurrentDatasets,
        backgroundColor: 'rgba(0, 214, 143, 0.3)',
        borderColor: '#00d68f',
        borderDash: [10, 5],
        tension: 0,
        fill: false,
        pointRadius: processedData.pointRadius3,
        hidden: true,
        yAxisID: 'yTemperature',
      },
      {
        label: 'Humidity',
        data: processedData.humidityDatasets,
        backgroundColor: 'rgba(0, 214, 143, 0.3)',
        borderColor: '#00d68f',
        tension: 0,
        fill: false,
        pointRadius: processedData.pointRadius4,
        yAxisID: 'yHumidity',
      },
    ],
  };

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    scales: {
      x: {
        type: 'time' as const,
        time: {
          unit: 'minute' as const,
          tooltipFormat: 'dd/MM - HH:mm',
          displayFormats: {
            minute: 'dd/MM - HH:mm',
          },
        },
        grid: {
          display: true,
        },
        ticks: {
          autoSkip: true,
        },
      },
      yTemperature: {
        position: 'left' as const,
        grid: {
          display: true,
        },
        ticks: {
          stepSize: 0.5,
          callback: (value: number | string) => `${value}°`,
        },
        min: processedData.minValue - 0.5,
        max: processedData.maxValue + 0.5,
      },
      yHumidity: {
        position: 'right' as const,
        grid: {
          display: false,
        },
        ticks: {
          stepSize: 5,
          callback: (value: number | string) => `${value}%`,
        },
        min: 15,
        max: 95,
      },
    },
    plugins: {
      legend: {
        display: true,
        position: 'top' as const,
      },
      tooltip: {
        mode: 'index' as const,
        intersect: false,
      },
    },
  };

  return (
    <div className="history-graph">
      <Line data={data} options={options} />
    </div>
  );
};

export default HistoryGraph;

// Dashboard/src/app/pages/history/historygraph/historygraph.component.ts
import { Component, OnDestroy, Input, OnChanges, SimpleChanges, ViewChild } from '@angular/core';
import { NbThemeService, NbColorHelper } from '@nebular/theme';
import { SensorDataEx } from '../../../@core/data/temperature-humidity';

@Component({
  selector: 'ngx-historygraph',
  styleUrls: ['./historygraph.component.scss'],
  templateUrl: './historygraph.component.html',
})
export class HistoryGraphComponent implements OnDestroy, OnChanges {
  @Input() sensorDataEx: SensorDataEx[] = [];
  @ViewChild('chartGraph') chartGraph; 
  data: any;
  options: any;
  themeSubscription: any;
  
  ngOnDestroy(): void {
    this.themeSubscription.unsubscribe();
  }

  ngOnChanges (changes: SimpleChanges) {

    for (let propName in changes) {  
      let change = changes[propName];
      if (change.currentValue == null) {
        continue;
      }

      if (propName == "sensorDataEx")
      {
        var maxValue: number = 0;
        var minValue: number = 100;
        var tempArray = [];
        var tValveArray = [];
        var tSchedArray = [];
        var tCurrentArray = [];
        var humidityArray = [];
        var pointRadius0=[];
        var pointRadius1=[];
        var pointRadius2=[];
        var pointRadius3=[];
        var pointRadius4=[];

        for (var _i = 0; _i < this.sensorDataEx.length; _i++)
        {
          if (_i > 0)
          {
            var dateNewValue = new Date(this.sensorDataEx[_i].ingestionTimestamp);
            var dateOldValue = new Date(this.sensorDataEx[_i-1].ingestionTimestamp);
            var diff = Math.abs(dateNewValue.getTime() - dateOldValue.getTime());
            var minutes = Math.floor(diff/60000);
            if (minutes > 15) //greater than deepsleep (10 minutes).
            {
              var dateIntermediate = new Date(dateNewValue.getTime() - (10*60*1000)); // 10 minutes before
              var dateIso = dateIntermediate.toISOString();
              tempArray.push({y: this.sensorDataEx[_i-1].temp, t: dateIso});
              tValveArray.push({y: this.sensorDataEx[_i-1].tValve, t: dateIso});
              tSchedArray.push({y: this.sensorDataEx[_i-1].tScheduledTarget, t: dateIso});
              tCurrentArray.push({y: this.sensorDataEx[_i-1].tCurrentTarget, t: dateIso});
              humidityArray.push({y: this.sensorDataEx[_i-1].humidity, t: dateIso});
              
              pointRadius0.push(1);
              pointRadius1.push(1);
              pointRadius2.push(1);                  
              pointRadius3.push(1);
              pointRadius4.push(1);
            }
          }
          tempArray.push({y: this.sensorDataEx[_i].temp, t: this.sensorDataEx[_i].ingestionTimestamp});
          tValveArray.push({y: this.sensorDataEx[_i].tValve, t: this.sensorDataEx[_i].ingestionTimestamp});
          tSchedArray.push({y: this.sensorDataEx[_i].tScheduledTarget, t: this.sensorDataEx[_i].ingestionTimestamp});
          tCurrentArray.push({y: this.sensorDataEx[_i].tCurrentTarget, t: this.sensorDataEx[_i].ingestionTimestamp});
          humidityArray.push({y: this.sensorDataEx[_i].humidity, t: this.sensorDataEx[_i].ingestionTimestamp});

          if (this.sensorDataEx[_i].setTempSended == true) {
            pointRadius0.push(4);
          } else {
            pointRadius0.push(1);
          }

          pointRadius1.push(1);
          pointRadius2.push(1);          
          pointRadius3.push(1);
          pointRadius4.push(1);

          if (maxValue < this.sensorDataEx[_i].temp && this.sensorDataEx[_i].temp > 0)  {
            maxValue = this.sensorDataEx[_i].temp;
          }
          if (maxValue < this.sensorDataEx[_i].tValve && this.sensorDataEx[_i].tValve > 0) {
            maxValue = this.sensorDataEx[_i].tValve;
          }
          if (maxValue < this.sensorDataEx[_i].tScheduledTarget && this.sensorDataEx[_i].tScheduledTarget > 0) {
            maxValue = this.sensorDataEx[_i].tScheduledTarget;
          }
          if (maxValue < this.sensorDataEx[_i].tCurrentTarget && this.sensorDataEx[_i].tCurrentTarget > 0) {
            maxValue = this.sensorDataEx[_i].tCurrentTarget;
          }


          if (minValue > this.sensorDataEx[_i].temp && this.sensorDataEx[_i].temp > 0) {
            minValue = this.sensorDataEx[_i].temp;
          }
          if (minValue > this.sensorDataEx[_i].tValve && this.sensorDataEx[_i].tValve > 0) {
            minValue = this.sensorDataEx[_i].tValve;
          }
          if (minValue > this.sensorDataEx[_i].tScheduledTarget && this.sensorDataEx[_i].tScheduledTarget > 0) {
            minValue = this.sensorDataEx[_i].tScheduledTarget;
          }
          if (minValue > this.sensorDataEx[_i].tCurrentTarget && this.sensorDataEx[_i].tCurrentTarget > 0) {
            minValue = this.sensorDataEx[_i].tCurrentTarget;
          }          
        }

        this.data.datasets[0].data = tempArray;
        this.data.datasets[1].data = tValveArray;
        this.data.datasets[2].data = tSchedArray;
        this.data.datasets[3].data = tCurrentArray;
        this.data.datasets[4].data = humidityArray;
        
        this.data.datasets[0].pointRadius = pointRadius0;
        this.data.datasets[1].pointRadius = pointRadius1;
        this.data.datasets[2].pointRadius = pointRadius2;
        this.data.datasets[3].pointRadius = pointRadius3;
        this.data.datasets[4].pointRadius = pointRadius4;


        this.options = {
          responsive: true,
          maintainAspectRatio: false,
          scales: {
            xAxes: [
              {
                type: 'time',
                time: {
                  unit: 'minute',
                  tooltipFormat: 'DD/MM - HH:mm',
                  displayFormats: {
                    minute: 'DD/MM - HH:mm'
                  }
                },
                gridLines: {
                  display: true,
                },
                ticks: {
                  autoSkip: true,
                  // maxTicksLimit: 30
                },                
              },
            ],
            yAxes: [
              { 
                id: 'yTemperature',
                gridLines: {
                  display: true,
                },
                ticks: {
                  beginAtZero: true,
                  stepSize: 0.5,
                  min: minValue - 0.5,
                  max: maxValue + 0.5,
                },
              },
              {
                id: 'yHumidity',
                gridLines: {
                  display: false,
                },
                ticks: {
                  beginAtZero: true,
                  stepSize: 5,
                  min: 15,
                  max: 95,
                },
                position: 'right',
              },
            ]          
          },
        };
        this.chartGraph.chart.update();
      }
    }
  }

  constructor(private theme: NbThemeService) {
    this.themeSubscription = this.theme.getJsTheme().subscribe(config => {

      const colors: any = config.variables;
      const chartjs: any = config.variables.chartjs;

      this.data = {
        labels: [],
        datasets: [{
          data: [],
          label: 'Temp',
          backgroundColor: NbColorHelper.hexToRgbA(colors.danger, 0.3),
          borderColor: colors.danger,
          lineTension: 0,        
          fill: false,
        }, {
          data: [],
          label: 'T Valve',
          backgroundColor: NbColorHelper.hexToRgbA(colors.primary, 0.3),
          borderColor: colors.primary,
          lineTension: 0,        
          fill: false,
          hidden: true,
        }, {
          data: [],
          label: 'T Scheduled',
          backgroundColor: NbColorHelper.hexToRgbA(colors.info, 0.3),
          borderDash: [10,5],
          fill: false,
          borderColor: colors.info,
          lineTension: 0,        
        },
        {
          data: [],
          label: 'T CurrentSched',
          backgroundColor: NbColorHelper.hexToRgbA(colors.success, 0.3),
          borderDash: [10,5],
          fill: false,
          borderColor: colors.success,
          lineTension: 0,        
          hidden: true,
        },
        {
          data: [],
          label: 'Humidity',
          backgroundColor: NbColorHelper.hexToRgbA(colors.success, 0.3),
          fill: false,
          borderColor: colors.info ,
          lineTension: 0,        
          hidden: false,
          yAxisID: 'yHumidity',
        },                
        ],
      };

      this.options = {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          xAxes: [
            {
              type: 'time',
              time: {
                unit: 'minute',
                tooltipFormat: 'DD/MM - HH:mm',
                displayFormats: {
                  minute: 'DD/MM - HH:mm'
                }
              },
              gridLines: {
                display: true,
                color: chartjs.axisLineColor,
              },
              ticks: {
                fontColor: chartjs.textColor,
              },
            },
          ],
          yAxes: [
            {
              gridLines: {
                display: true,
                color: chartjs.axisLineColor,
              },
              ticks: {
                fontColor: chartjs.textColor,
                beginAtZero: true,
                stepSize: 0.5,
                min: 16,
                max: 23,
              },
            },
            {
              id : 'yHumidity',
              gridLines: {
                display: true,
                color: chartjs.axisLineColor,
              },
              ticks: {
                fontColor: chartjs.textColor,
                beginAtZero: true,
                stepSize: 5,
                min: 15,
                max: 95,
              },
              position: 'right',
            },
          ],
        },
        legend: {
          labels: {
            fontColor: chartjs.textColor,
          },
        },
      };
    });
  }
}


    <chart #chartGraph type="line" [data]="data" [options]="options"></chart>

<!-- <nb-card size="large">
  <div class="chart-container">
   <div class="chart-header">
      <div class="header-stats">
        <div class="stats-block">
          <div class="subtitle">Current Temperature:</div>
          <div>
            <span class="value">20</span>
            <span class="unit">°C</span>
          </div>
        </div>
       
      </div>

      <div class="dropdown"
           [ngClass]="{ 'ghost-dropdown': currentTheme === 'corporate' }"
           ngbDropdown>
        <button type="button" ngbDropdownToggle class="btn"
                [ngClass]="{ 'btn-outline-success': currentTheme == 'default', 'btn-primary': currentTheme != 'default'}">
          {{ type }}
        </button>
        <ul class="dropdown-menu" ngbDropdownMenu>
          <li class="dropdown-item" *ngFor="let t of types" (click)="type = t">{{ t }}</li>
        </ul>
      </div>
    </div>
    <chart type="line" [data]="data" [options]="options"></chart>
  </div>
</nb-card> -->
